version: "3.8"

services:
  analytics_env:
    image: jupyter/scipy-notebook:latest
    container_name: data_analysis_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=brandware2026
    working_dir: /home/jovyan/work